"""Add station_mapping table for PostgreSQL compatibility

Revision ID: c9217afd089b
Revises: 72fc10f0db92
Create Date: 2025-06-13 09:18:30.270817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9217afd089b'
down_revision: Union[str, None] = '72fc10f0db92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station_mapping')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_mapping',
    sa.Column('uuid_station_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('numeric_station_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('station_name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('uuid_station_id')
    )
    # ### end Alembic commands ###
